services:
  webserver-db:
    build: ./database
    ports:
      - 27017:27017
    networks:
      - project-network

  backend:
    build: ./backend
    ports:
      - 3000:3000
    networks:
      - project-network
    depends_on:
      - webserver-db

  frontend:
    build: ./frontend
    ports:
      - 8080:80

networks:
  project-network:
    name: webserver-network
    driver: bridge
    